sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7

install:
  - composer install --prefer-source --no-interaction
  - composer dump-autoload -o

script:
  - bin/phpspec run

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
