language: php

php:
  - 5.5
  - 5.6
  - 7

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer dump-autoload -o

script:
  # move specs to App folder under spec due travis issue reading psr4_prefix
  - mkdir spec/App
  - mv spec/*.php spec/App/
  - ./bin/phpspec run --config ./phpspec.yml

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
