language: php

php:
  - 5.5
  - 5.6
  - 7

install:
  - /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/composer self-update
  - composer install

script:
  - bin/phpspec run

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
