sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7

install:
  - composer install

script:
  - bin/phpspec run

after_script:
  - bin/phpspec run -v

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
